[build-system]
requires = ["uv_build>=0.12.17,<1.0.0"]
build-backend = "uv_build"

[project]
name = "dartboard-ia"
version = "1.0.0a1"
authors = [
    {name = "DigitalDragon"}
]
description = "Internet Archive upload management tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "internetarchive>=5.0.3",
    "dataclasses-json",
    "watchdog",
]

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "pytest"
]

[project.urls]
repository = "https://github.com/DigitalDwagon/dartboard"

[tool.uv.build-backend]
module-name = ["dartboard"]
module-root = ""

[project.scripts]
dartboard = "dartboard.main:main"

